name: Manual
on:
  workflow_dispatch: # 手動トリガー
    inputs: # 入力パラメータはinputsキーで定義
      greeting:
        type: string
        default: "Hello"
        required: true
        description: "Greeting message"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting}}"
